### PR TITLE
A complete overhaul of the myriadcoin.org website.

### PR DESCRIPTION
**Pull request by braydo25**
Hello! I'd like to propose this completely rebuilt website for myriadcoin.org. It updates the overall design to a more modern look, while maintaining the primary content on the current site.

The new website is entirely static and does not require a backend. It's preferred deployment destination would be AWS' S3 & CloudFront for the fastest experience for end users. Alternatively, you can simply run the build command and copy the build directory contents to wherever the current Myriad site is being hosted.

Translations and automatic language assumption is baked in - If you're in China, and Accept-Language header specified chinese, you'll be served the Chinese version of the website for example.

To run the site locally, checkout the readme: https://github.com/braydo25/website/blob/86e63be65c469b1aa4c27b2d5f6a3ad7014d1917/README.md

You can see my post in the Myriad subreddit related to it's development: https://www.reddit.com/r/myriadcoin/comments/7lcxjv/a_new_website_for_myriad_with_screenshots/

Let me know if anything needs changing or is to your disliking. I'm more than happy to help get this setup on AWS if that's what the current Myriad team prefers. Looking forward to helping in any way I can.

### CODE REVIEW

**Comment by braydo25** [comment]
Ahh, I should of added - with the AWS deployment route as outlined in the readme, after setting up the .env file you'd simply run `npm run deploy`

**Comment by cryptapus** [comment]
Thanks for the proposal. We have a few guidelines that I think we've come to some agreement in the past:

1. It needs to be maintainable after the original author disappears
2. It needs to address all aspects of the current site

Item 2 is where most folks get hung up since that usually includes translations. It looks like you've addressed this completely?

Of coarse I suspect we also need large community support.

Nice looking site!

**Comment by braydo25** [comment]
Thanks @cryptapus,

As far as concerns.

1 - This shouldn't be a problem, I've tried to streamline development as much as possible with the tools used. The README has everything needed to get started with development. From there it's a simple matter of editing the HTML / Sass (Basically CSS) / Javascript in the src directory. the Cloudforge library handles everything else from auto refreshes in the launched browser window on any code changes, generating builds, or deploying.

2 - I believe everything is included. All the content on the site was taken from the existing myriadcoin.org, I went through basically every page making sure to not leave anything out.

Additionally, I think for the sake of the perceived image for Myriad it would be appropriate to setup and force SSL (https) only on the site. I'd imagine the overall perceived image, trustworthiness and initial impression of the coin would be perceived as higher from newcomers to the site.

**Comment by braydo25** [comment]
@cryptapus, @nzsquirrell, @8bitcoder 

So you can test the site live, I've went ahead and setup a stable production environment on AWS using S3 and CloudFront. The AWS account used is under a GMAIL account I created (myriadcoinaws@gmail.com) - I can pass on all the credentials for the root AWS login and Gmail account if you decide to move to S3 - which is already currently setup. For the sake of future proofing and maintaining, nothing will need to be managed on AWS after the initial setup. To deploy changes you'd just need to set the required info / credentials in the .env file, and run `npm run deploy`. It'll handle everything else. I'll also pass along all those credentials to whomever typically manages them.

To enable SSL on the CloudFront setup if you decide to point myriadcoin.org here, you'll need to add the following CNAME entry on the myriadcoin DNS settings to authorize an SSL cert to be issued on the AWS end. 

DNS Record
Type: `CNAME`
Name: `_ac5b69e0e2e26164c8b153e64ba6ac63`
Value: `_88194ec453d03e1b8d81b2fe28872d31.acm-validations.aws`

To get the site online at this point, all you have to do is update the myriadcoin.org DNS settings to point to `dncm3e0t911fx.cloudfront.net` - You'll need to point to this hostname and not the underlying IP as it's not static. You can do this by deleting the A record and setting the www CNAME to point to `dncm3e0t911fx.cloudfront.net`.

**Comment by 8bitcoder** [comment]
Looks good. 

Ack for go-ahead.

I want to do a deployment to a test server at some stage before we take it live. Would like a similar setup as we have now where the web site automatically updates from the Github repository.

**Comment by braydo25** [comment]
Hey @8bitcoder - If you don't care about keeping us on AWS I can very quickly get this setup with AWS' CodePipeline. Basically anytime the `website` repo master branch gets update (Or whatever branch you consider the production branch) - It will automate the deployment of changes. Would that work?

**Comment by braydo25** [comment]
To setup CodePipelin I'd need access to an account that has admin access on the website repo, or admin access to the repo for my own account into order to let AWS' CodePipeline service access the repo's webhooks for automating deployments whenever it sees a new commit come in on master.

**Comment by braydo25** [comment]
Also, who should I forward the AWS account credentials to? Presumably you @8bitcoder, but who else?

**Comment by 8bitcoder** [comment]
www.myriadcoin.org now points to the new site.

**Pull request merged**
