### PR TITLE
Add Android wallets

### PR DESCRIPTION
**Pull request by Angristan**
I don't know if we should call all the links "Google Play", but at least we should add these wallets :)

### CODE REVIEW

**Comment by cryptapus** [comment]
NACK on coinomi. It's not open source.

**Comment by Angristan** [comment]
As you want. :)

What about the first one, do you know if the're any source code available? I can't find any.

And the third one "isn't available in my country".

**Comment by cryptapus** [comment]
I thought /u/_wlc_ had a github for it, but can't seem to locate it at the moment. Worth checking.

**Comment by cryptapus** [comment]
Confirmed from wlc:

https://github.com/wlc-/myriadjs

Drop coinomi and I'm ACK

**Comment by cryptapus** [comment]
Changed your ordering and added some description. I'll merge this in ~1day if no objections.

Thanks!

**Pull request merged**
