### PR TITLE
Website Overhaul

### PR DESCRIPTION
**Pull request by iamoscaroneill**
### Changes
- Created a fresh minimalistic look
- Links to exchanges where XMY is no longer trading have been removed
- Links to merchant pages where XMY is no longer accepted have been removed
- Added a dropdown menu that covers the viewport

### Scenario
Should this pull request be accepted, the `package.json` must be updated with additional scripts in order to deploy as a react application to Github pages

### Redesign
myriad

### Menu
myriad-menu

### CODE REVIEW

**Comment by roarde** [comment]
This merge would come with a bit of history:  https://github.com/oscar-oneill/myriadwebsite/commit/c71fd1f13111f578fa88c500db12fcf46b021fe5         
"Showing 35,070 changed files with 3,410,786 additions and 11,854 deletions."             
                     
As it is, more than it's good to carry around. Problems with Git-workflow happen, but I'm honestly interested in how 35K files would be pulled into it.

**Comment by iamoscaroneill** [comment]
> This merge would come with a bit of history: [oscar-oneill@c71fd1f](https://github.com/oscar-oneill/myriadwebsite/commit/c71fd1f13111f578fa88c500db12fcf46b021fe5) "Showing 35,070 changed files with 3,410,786 additions and 11,854 deletions."
> 
> As it is, more than it's good to carry around. Problems with Git-workflow happen, but I'm honestly interested in how 35K files would be pulled into it.

- Those 35K files are part of React's `node_modules` folder where all of its dependencies are held. As dependencies are installed/uninstalled, folders and files will be added/removed from that directory automatically. There isn't much need to adjust anything there.
- All that said, the `node_modules` directory was removed in a subsequent commit. React Apps can be deployed online **without** it and can be built using `package.json`, see this [Repo](https://github.com/oscar-oneill/yesterday-redesign).

**Comment by cryptapus** [comment]
Thanks for the submission!

Large overhauls of the website look-and-feel should have community consensus. I would suggest that you create a reddit thread to involve the non-developer community to the discussion.

https://www.reddit.com/r/myriadcoin/

**Comment by iamoscaroneill** [comment]
> Thanks for the submission!
> 
> 
> 
> Large overhauls of the website look-and-feel should have community consensus. I would suggest that you create a reddit thread to involve the non-developer community to the discussion.
> 
> 
> 
> https://www.reddit.com/r/myriadcoin/

Done. I see you're a mod there, could you approve the post? Thanks!

**Pull request closed without merging**
